// GENERATED CODE - DO NOT MODIFY BY HAND

part of 'stock_entry.dart';

// **************************************************************************
// JsonSerializableGenerator
// **************************************************************************

_$StockEntryImpl _$$StockEntryImplFromJson(Map<String, dynamic> json) =>
    _$StockEntryImpl(
      name: json['name'] as String?,
      owner: json['owner'] as String?,
      creation: json['creation'] as String?,
      modified: json['modified'] as String?,
      modifiedBy: json['modified_by'] as String?,
      docstatus: (json['docstatus'] as num?)?.toInt(),
      idx: (json['idx'] as num?)?.toInt(),
      workflowState: json['workflow_state'] as String?,
      namingSeries: json['naming_series'] as String?,
      stockEntryType: json['stock_entry_type'] as String?,
      outgoingStockEntry: json['outgoing_stock_entry'] as String?,
      purpose: json['purpose'] as String?,
      addToTransit: (json['add_to_transit'] as num?)?.toInt(),
      workOrder: json['work_order'] as String?,
      purchaseOrder: json['purchase_order'] as String?,
      subcontractingOrder: json['subcontracting_order'] as String?,
      deliveryNoteNo: json['delivery_note_no'] as String?,
      salesInvoiceNo: json['sales_invoice_no'] as String?,
      pickList: json['pick_list'] as String?,
      purchaseReceiptNo: json['purchase_receipt_no'] as String?,
      assetRepair: json['asset_repair'] as String?,
      ewaybill: json['ewaybill'] as String?,
      company: json['company'] as String?,
      postingDate: json['posting_date'] as String?,
      postingTime: json['posting_time'] as String?,
      setPostingTime: (json['set_posting_time'] as num?)?.toInt(),
      inspectionRequired: (json['inspection_required'] as num?)?.toInt(),
      applyPutawayRule: (json['apply_putaway_rule'] as num?)?.toInt(),
      fromBom: (json['from_bom'] as num?)?.toInt(),
      useMultiLevelBom: (json['use_multi_level_bom'] as num?)?.toInt(),
      bomNo: json['bom_no'] as String?,
      fgCompletedQty: (json['fg_completed_qty'] as num?)?.toDouble(),
      processLossPercentage:
          (json['process_loss_percentage'] as num?)?.toDouble(),
      processLossQty: (json['process_loss_qty'] as num?)?.toDouble(),
      fromWarehouse: json['from_warehouse'] as String?,
      sourceWarehouseAddress: json['source_warehouse_address'] as String?,
      sourceAddressDisplay: json['source_address_display'] as String?,
      toWarehouse: json['to_warehouse'] as String?,
      targetWarehouseAddress: json['target_warehouse_address'] as String?,
      targetAddressDisplay: json['target_address_display'] as String?,
      scanBarcode: json['scan_barcode'] as String?,
      customBarcode: json['custom_barcode'] as String?,
      taxCategory: json['tax_category'] as String?,
      taxesAndCharges: json['taxes_and_charges'] as String?,
      totalTaxes: (json['total_taxes'] as num?)?.toDouble(),
      baseGrandTotal: (json['base_grand_total'] as num?)?.toDouble(),
      totalOutgoingValue: (json['total_outgoing_value'] as num?)?.toDouble(),
      totalIncomingValue: (json['total_incoming_value'] as num?)?.toDouble(),
      valueDifference: (json['value_difference'] as num?)?.toDouble(),
      totalAdditionalCosts:
          (json['total_additional_costs'] as num?)?.toDouble(),
      supplier: json['supplier'] as String?,
      supplierName: json['supplier_name'] as String?,
      supplierAddress: json['supplier_address'] as String?,
      addressDisplay: json['address_display'] as String?,
      billFromAddress: json['bill_from_address'] as String?,
      billFromGstin: json['bill_from_gstin'] as String?,
      billFromGstCategory: json['bill_from_gst_category'] as String?,
      billToAddress: json['bill_to_address'] as String?,
      billToGstin: json['bill_to_gstin'] as String?,
      billToGstCategory: json['bill_to_gst_category'] as String?,
      placeOfSupply: json['place_of_supply'] as String?,
      shipFromAddress: json['ship_from_address'] as String?,
      shipToAddress: json['ship_to_address'] as String?,
      transporter: json['transporter'] as String?,
      gstTransporterId: json['gst_transporter_id'] as String?,
      lrNo: json['lr_no'] as String?,
      vehicleNo: json['vehicle_no'] as String?,
      distance: (json['distance'] as num?)?.toInt(),
      transporterName: json['transporter_name'] as String?,
      modeOfTransport: json['mode_of_transport'] as String?,
      lrDate: json['lr_date'] as String?,
      gstVehicleType: json['gst_vehicle_type'] as String?,
      project: json['project'] as String?,
      selectPrintHeading: json['select_print_heading'] as String?,
      letterHead: json['letter_head'] as String?,
      isOpening: json['is_opening'] as String?,
      remarks: json['remarks'] as String?,
      perTransferred: (json['per_transferred'] as num?)?.toDouble(),
      totalAmount: (json['total_amount'] as num?)?.toDouble(),
      jobCard: json['job_card'] as String?,
      amendedFrom: json['amended_from'] as String?,
      creditNote: json['credit_note'] as String?,
      isReturn: (json['is_return'] as num?)?.toInt(),
    );

Map<String, dynamic> _$$StockEntryImplToJson(_$StockEntryImpl instance) =>
    <String, dynamic>{
      'name': instance.name,
      'owner': instance.owner,
      'creation': instance.creation,
      'modified': instance.modified,
      'modified_by': instance.modifiedBy,
      'docstatus': instance.docstatus,
      'idx': instance.idx,
      'workflow_state': instance.workflowState,
      'naming_series': instance.namingSeries,
      'stock_entry_type': instance.stockEntryType,
      'outgoing_stock_entry': instance.outgoingStockEntry,
      'purpose': instance.purpose,
      'add_to_transit': instance.addToTransit,
      'work_order': instance.workOrder,
      'purchase_order': instance.purchaseOrder,
      'subcontracting_order': instance.subcontractingOrder,
      'delivery_note_no': instance.deliveryNoteNo,
      'sales_invoice_no': instance.salesInvoiceNo,
      'pick_list': instance.pickList,
      'purchase_receipt_no': instance.purchaseReceiptNo,
      'asset_repair': instance.assetRepair,
      'ewaybill': instance.ewaybill,
      'company': instance.company,
      'posting_date': instance.postingDate,
      'posting_time': instance.postingTime,
      'set_posting_time': instance.setPostingTime,
      'inspection_required': instance.inspectionRequired,
      'apply_putaway_rule': instance.applyPutawayRule,
      'from_bom': instance.fromBom,
      'use_multi_level_bom': instance.useMultiLevelBom,
      'bom_no': instance.bomNo,
      'fg_completed_qty': instance.fgCompletedQty,
      'process_loss_percentage': instance.processLossPercentage,
      'process_loss_qty': instance.processLossQty,
      'from_warehouse': instance.fromWarehouse,
      'source_warehouse_address': instance.sourceWarehouseAddress,
      'source_address_display': instance.sourceAddressDisplay,
      'to_warehouse': instance.toWarehouse,
      'target_warehouse_address': instance.targetWarehouseAddress,
      'target_address_display': instance.targetAddressDisplay,
      'scan_barcode': instance.scanBarcode,
      'custom_barcode': instance.customBarcode,
      'tax_category': instance.taxCategory,
      'taxes_and_charges': instance.taxesAndCharges,
      'total_taxes': instance.totalTaxes,
      'base_grand_total': instance.baseGrandTotal,
      'total_outgoing_value': instance.totalOutgoingValue,
      'total_incoming_value': instance.totalIncomingValue,
      'value_difference': instance.valueDifference,
      'total_additional_costs': instance.totalAdditionalCosts,
      'supplier': instance.supplier,
      'supplier_name': instance.supplierName,
      'supplier_address': instance.supplierAddress,
      'address_display': instance.addressDisplay,
      'bill_from_address': instance.billFromAddress,
      'bill_from_gstin': instance.billFromGstin,
      'bill_from_gst_category': instance.billFromGstCategory,
      'bill_to_address': instance.billToAddress,
      'bill_to_gstin': instance.billToGstin,
      'bill_to_gst_category': instance.billToGstCategory,
      'place_of_supply': instance.placeOfSupply,
      'ship_from_address': instance.shipFromAddress,
      'ship_to_address': instance.shipToAddress,
      'transporter': instance.transporter,
      'gst_transporter_id': instance.gstTransporterId,
      'lr_no': instance.lrNo,
      'vehicle_no': instance.vehicleNo,
      'distance': instance.distance,
      'transporter_name': instance.transporterName,
      'mode_of_transport': instance.modeOfTransport,
      'lr_date': instance.lrDate,
      'gst_vehicle_type': instance.gstVehicleType,
      'project': instance.project,
      'select_print_heading': instance.selectPrintHeading,
      'letter_head': instance.letterHead,
      'is_opening': instance.isOpening,
      'remarks': instance.remarks,
      'per_transferred': instance.perTransferred,
      'total_amount': instance.totalAmount,
      'job_card': instance.jobCard,
      'amended_from': instance.amendedFrom,
      'credit_note': instance.creditNote,
      'is_return': instance.isReturn,
    };
