// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAoCHSIjKS-qkxf5GeNpwiSql2AgTClBp8',
    appId: '1:953245490750:web:6773a51abee19372963b6f',
    messagingSenderId: '953245490750',
    projectId: 'aashirwad-ayurvedha',
    authDomain: 'aashirwad-ayurvedha.firebaseapp.com',
    storageBucket: 'aashirwad-ayurvedha.firebasestorage.app',
    measurementId: 'G-M0BT8KLQ0L',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBf3dDrb4-CSkKJ2cvl13eNQTkmAibVbIA',
    appId: '1:953245490750:android:f30fb9096408b136963b6f',
    messagingSenderId: '953245490750',
    projectId: 'aashirwad-ayurvedha',
    storageBucket: 'aashirwad-ayurvedha.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD_kXuYljqQaQVPHAWjQt0fRZD5MHEqWso',
    appId: '1:953245490750:ios:53e8ea06ba55a19f963b6f',
    messagingSenderId: '953245490750',
    projectId: 'aashirwad-ayurvedha',
    storageBucket: 'aashirwad-ayurvedha.firebasestorage.app',
    iosBundleId: 'in.easycloud.aashirwad',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD_kXuYljqQaQVPHAWjQt0fRZD5MHEqWso',
    appId: '1:953245490750:ios:53e8ea06ba55a19f963b6f',
    messagingSenderId: '953245490750',
    projectId: 'aashirwad-ayurvedha',
    storageBucket: 'aashirwad-ayurvedha.firebasestorage.app',
    iosBundleId: 'in.easycloud.aashirwad',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAoCHSIjKS-qkxf5GeNpwiSql2AgTClBp8',
    appId: '1:953245490750:web:6fd92286097952de963b6f',
    messagingSenderId: '953245490750',
    projectId: 'aashirwad-ayurvedha',
    authDomain: 'aashirwad-ayurvedha.firebaseapp.com',
    storageBucket: 'aashirwad-ayurvedha.firebasestorage.app',
    measurementId: 'G-E2J31DZX77',
  );
}
